timer: 10
radius: 10
cancelOn:
  playerPVP: true
  move: true
  damage: true
timerAndRadius: true
globalWarpsCountTowardsTotal: false
defaultMaxWarps: 50
warpInviteTimeout: 120
useMultiverse: true